config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :posts do
      collection do
        get "notification_show/:id", action: 'notification_show', as: :notification_show
      end
    end
    collection do
      get "search_friend"
      get "add_friend_request"
      get "confirm_friend_request"
      get "confirm_friend_request_ajax"
      get "cancel_friend_request"
      get "cancel_friend_request_ajax"
      get "load_received_friend_request_list"
      get "post_create"
      get "post_like"
      get "show_all_likes"
      get "post_delete"
      get "post_comment"
      get "pagination_sample"
      get "load_notification"
      get "all_notification"
    end
  end
  resources :messages do
    collection do
      get "message_load"
    end
  end

  root :to => redirect('/users')

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable,
         :recoverable, :rememberable, :trackable, :validatable

  # devise :omniauthable, :omniauth_providers => [:facebook]
  # devise :omniauthable, :omniauth_providers => [:twitter]

  mount_uploader :profilepic, ProfilepicUploader

  has_many :sent_messages, class_name: "Message", foreign_key: "sender_id", dependent: :destroy
  has_many :received_messages, class_name: "Message", foreign_key: "recipient_id", dependent: :destroy

  has_many :sent_notification, class_name: "Notification", foreign_key: "maker_id",dependent: :destroy
  has_many :received_notification, class_name: "Notification", foreign_key: "recipient_id", dependent: :destroy

  has_many :sent_request, class_name: "UserFriend", foreign_key: "sender_id", dependent: :destroy
  has_many :received_request, class_name: "UserFriend", foreign_key: "recipient_id", dependent: :destroy

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy


  def self.from_omniauth_linkedin(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      if(user.email.blank?)
        user.email = auth.info.email
      end
      user.username=auth.info.username
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.profilepic = auth.info.image # assuming the user model has an image

      # user.save!
      UserMailer.signup_confirmation(user).deliver
    end
  end
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.username=auth.info.username
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.profilepic = auth.info.image # assuming the user model has an image

      #Image save
      # r = open("#{auth.info.image}")
      # bytes = r.read
      # img = Magick::Image.from_blob(bytes).first
      # fmt = img.format
      # data=StringIO.new(bytes)
      # data.class.class_eval { attr_accessor :original_filename, :content_type }
      # data.original_filename = Time.now.to_i.to_s+"."+fmt
      # data.content_type='image.jpeg'
      # user.remote_profilepic_url = auth.info.image


      # user.save!
      UserMailer.signup_confirmation(user).deliver
    end
  end



end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Twitter") if is_navigational_format?
    else
      session["devise.twitter_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def linkedin
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Linkedin") if is_navigational_format?
    else
      session["devise.linkedin_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
  # alias_method :linkedin, :all
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :common_method, :get_friend_list,
                :except => [:search_friend,:add_friend_request,
                            :confirm_friend_request,:confirm_friend_request_ajax,
                            :cancel_friend_request,:cancel_friend_request_ajax,:load_notification,:post_comment,
                            :post_create,:post_delete,:post_like,:show_all_likes,:load_received_friend_request_list,
                            :load_notification, :index]

  def index
    @users=User.all
    @post=Post.new
    @user_p=User.new
    @cuuser=current_user
    friend1=current_user.sent_request.where("friend_type = ?",1)
    friend2=current_user.received_request.where("friend_type = ?",1)
    @friend_list=[]
    @all_posts=[]
    if friend1.any?
      friend1.each do |frnd|
        temp_user=User.find(frnd.recipient_id)
        @friend_list<<temp_user
        pts=temp_user.posts
        if pts.any?
          pts.each do |p|
            @all_posts<<p
          end
        end

      end
    end
    if friend2.any?
      friend2.each do |frnd|
        temp_user=User.find(frnd.sender_id)
        @friend_list<<temp_user
        pts=temp_user.posts
        if pts.any?
          pts.each do |p|
            @all_posts<<p
          end
        end
      end
    end
    my_pts=current_user.posts
    if my_pts.any?
      my_pts.each do |p|
        @all_posts<<p
      end
    end
    @all_posts= @all_posts.sort_by &:created_at
    @all_posts.reverse!
  end

  def show
    @user=User.find(params[:id]) rescue nil
    if @user
      @friend_comment='Add Friend'
      if current_user==@user
        @friend_comment='Me'
      else
        frndtype1=current_user.sent_request.where("friend_type = ? AND recipient_id = ?", 1 , params[:id])
        frndtype2=current_user.received_request.where("friend_type = ? AND sender_id = ?", 1, params[:id])
        frndtype3=current_user.received_request.where("friend_type = ? AND sender_id = ?", 2, params[:id])
        frndtype4=current_user.sent_request.where("friend_type = ? AND recipient_id = ?", 2, params[:id])
        if frndtype1.any? || frndtype2.any?
          @friend_comment='Friend'
        end
        if frndtype3.any?
          @friend_comment='Confirm or Cancel'
        end
        if frndtype4.any?
          @friend_comment='Request Sent'
        end
      end
    else
      redirect_to users_path
    end
  end


  def new
    @user=User.new
  end

  def search_friend
    @searched_friend=User.where("email like ?", "%#{params[:friend_name]}%").first(7)
  end

  def add_friend_request
    userfrnd=UserFriend.new({:sender_id=>current_user.id, :recipient_id=>params[:user_id], :friend_type=>2})
    if userfrnd.save()
      redirect_to user_path(params[:user_id])
    end
  end

  def confirm_friend_request
    usrfrnd=UserFriend.find_by("sender_id = ? AND recipient_id = ?", params[:user_id], current_user.id)
    if usrfrnd.update(:friend_type=> 1)
      redirect_to user_path(params[:user_id])
    end
  end

  def confirm_friend_request_ajax
    usrfrnd=UserFriend.find_by("sender_id = ? AND recipient_id = ?", params[:user_id], current_user.id)
    usrfrnd.update(:friend_type=> 1)
  end

  def cancel_friend_request
    usrfrnd=UserFriend.find_by("sender_id = ? AND recipient_id = ?", params[:user_id], current_user.id)
    if usrfrnd.destroy()
      redirect_to user_path(params[:user_id])
    end
  end

  def cancel_friend_request_ajax
    usrfrnd=UserFriend.find_by("sender_id = ? AND recipient_id = ?", params[:user_id], current_user.id)
    usrfrnd.destroy()
  end

  def load_received_friend_request_list
    usrfrnd=current_user.received_request.where("friend_type = ?", 2)
    @all_Friend_request=[]
    usrfrnd.each do |us|
      user=User.find(us.sender_id)
      @all_Friend_request<<user;
    end

  end

  def post_create

  end
  def post_like
      post=Post.find(params[:post_id])
      unless post.nil?
        already_liked=post.likes.where(:user_id=>current_user.id)
        unless already_liked.any?
          like=post.likes.create(:user_id=>current_user.id)
          unless current_user==post.user
            notify_body='likes your post'
            notify=post.notifications.build(:body=>notify_body,:seen=>false,:maker_id=>current_user.id,:recipient_id=>post.user.id)
            notify.save
          end
        end
      end
  end

  def show_all_likes
    post=Post.find(params[:post_id])
    @all_likes=post.likes
  end

  def post_delete
    @post=Post.find(params[:post_id])
    if @post.user.id==current_user.id
      if @post.destroy
        @post_deleted_falg="true"
      else
        @post_deleted_falg="false"
      end
    end
  end

  def post_comment
    @post=Post.find(params[:post_id])
    @comment=@post.comments.new(:user_id=>current_user.id,:body=>params[:body])
    if @comment.save
      @post_comment_flag="true"
      unless current_user==@post.user
        notify_body='comments on your post'
        notify=@post.notifications.build(:body=>notify_body,:seen=>false,:maker_id=>current_user.id,:recipient_id=>@post.user.id)
        notify.save
      end
      commented_user=[]
      if @post.comments.any?
        commenter=@post.comments
        commented_user=commenter+commenter
        commented_user.uniq! {|e| e[:user_id] }
        commented_user.each do |cmnt|
          unless current_user==cmnt.user
            unless @post.user==cmnt.user
              notify_body='comments on '+@post.user.name+"'s post of you"
              notify=@post.notifications.build(:body=>notify_body,:seen=>false,:maker_id=>current_user.id,:recipient_id=>cmnt.user.id)
              notify.save
            end
          end
        end
      end
    else
      @post_comment_flag="false"
    end
  end

  def load_notification
    @all_notifications=current_user.received_notification.last(7)
  end

  def pagination_sample
    @users = User.order(:name).page(params[:page]).per(2)
    # raise User.all.count.inspect
  end

  def all_notification
    @all_notifications=current_user.received_notification
  end

  protected
  def common_method
    @user_id=current_user.id
  end

  def user_params
    params.require(:user).permit(:name, :email, :username, :password, :reset_password);
  end
  def comment_params
    params.require(:comment).permit(:like).merge(user_id: current_user.id, body: params[:body]);
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_load_friend_request.html.erb
<% if @all_Friend_request.any? %>
    <% @all_Friend_request.each do |frnd_reqst| %>
        <div data-userinfo="<%= frnd_reqst.to_json %>">
          <%= link_to frnd_reqst.email, frnd_reqst, :class => 'seperate_class' %>
          <span class="seperate_class confirm_request">Confirm</span>
          <span class="seperate_class cancel_request">Cancel</span>
        </div>
    <% end %>
<% else %>
    <div>None</div>
<% end %>

app/views/users/_load_notification_partial_view.html.erb
<% if @all_notifications.any? %>
    <div class="notification_box">
      <% @all_notifications.each do |notify| %>
          <%= link_to notification_show_user_posts_path(:user_id=>notify.post.user.id,:id=>notify.id) do %>
              <% if notify.seen  %>
                  <div class="every_notification">
                    <div class="image_holder">
                      <% if notify.maker.profilepic %>
                          <%= image_tag(notify.maker.profilepic,:class => "notify_image")%>
                      <% else %>
                          <%= image_tag('/image/profile-image2.gif',:class => "notify_image")%>
                      <% end %>
                    </div>
                    <div class="body_holder">
                      <span class="maker_mane"><%= notify.maker.name %></span>
                      <span class="body"><%= notify.body %></span>
                    </div>
                    <div style="clear: both"></div>
                  </div>
              <% else %>
                  <div class="every_notification unread_notification">
                    <div class="image_holder">
                      <% if notify.maker.profilepic %>
                          <%= image_tag(notify.maker.profilepic,:class => "notify_image")%>
                      <% else %>
                          <%= image_tag('/image/profile-image2.gif',:class => "notify_image")%>
                      <% end %>
                    </div>
                    <div class="body_holder">
                      <span class="maker_mane"><%= notify.maker.name %></span>
                      <span class="body"><%= notify.body %></span>
                    </div>
                    <div style="clear: both"></div>
                  </div>
              <% end %>
          <% end %>
      <% end %>
      <%= link_to all_notification_users_path do %>
      <div class="show_all_notification">All Notification</div>
      <% end %>
    </div>
<% else %>
    <div class="notification_box">
        <div>
            None
        </div>
    </div>
<% end %>

app/views/users/_post_comment.html.erb
<div class="single_comment">
  <% if current_user.profilepic.present? %>
      <%= link_to image_tag(current_user.profilepic, :border => 0, :alt => '', :title => current_user.name), user_path(current_user), :class => ''%>
  <% else %>
      <%= link_to image_tag("/image/profile-image2.gif", :border => 0, :alt => '', :title => current_user.name), user_path(current_user), :class => ''%>
  <% end %>
  <span class="commenter"><%= link_to current_user.name, user_path(current_user) %></span>
  <span class="comment_body"> <%= @comment.body %></span>
</div>

app/views/users/_searched_friendListLoad.html.erb
<% if @searched_friend.any?  %>
    <% @searched_friend.each do |frnd|  %>

          <%= link_to user_path(frnd) do %>
          <div class="every_searched_friend">
            <div class="left_div">
              <span class="email"><%= frnd.email %></span>
            </div>
            <div class="right_div">
              <% if frnd.profilepic.present? %>
                  <%= image_tag(frnd.profilepic) %>
              <% else %>
                  <%= image_tag('/image/profile-image2.gif') %>
              <% end %>
            </div>
            <div style="clear:both;"></div>
          </div>
          <% end %>

    <% end %>
<% end %>

app/views/users/_show_all_likes.html.erb
<div class="alllikesholder">
  <% @all_likes.each do |like| %>
      <div class="likes_row">
      <% if like.user.id==@user_id %>
            <%= "You" %>
      <% else %>
            <%= like.user.name %>
      <% end %>
      </div>
  <% end %>
</div>

app/views/users/all_notification.html.erb
<div class="all_notification_container">
  <% @all_notifications.each do |notify| %>
      <%= link_to notification_show_user_posts_path(:user_id=>notify.post.user.id,:id=>notify.id) do %>
          <% if notify.seen  %>
              <div class="every_notification">
                <div class="image_holder">
                  <% if notify.maker.profilepic %>
                      <%= image_tag(notify.maker.profilepic,:class => "notify_image")%>
                  <% else %>
                      <%= image_tag('/image/profile-image2.gif',:class => "notify_image")%>
                  <% end %>
                </div>
                <div class="body_holder">
                  <span class="maker_mane"><%= notify.maker.name %></span>
                  <span class="body"><%= notify.body %></span>
                </div>
                <div style="clear: both"></div>
              </div>
          <% else %>
              <div class="every_notification unread_notification">
                <div class="image_holder">
                  <% if notify.maker.profilepic %>
                      <%= image_tag(notify.maker.profilepic,:class => "notify_image")%>
                  <% else %>
                      <%= image_tag('/image/profile-image2.gif',:class => "notify_image")%>
                  <% end %>
                </div>
                <div class="body_holder">
                  <span class="maker_mane"><%= notify.maker.name %></span>
                  <span class="body"><%= notify.body %></span>
                </div>
                <div style="clear: both"></div>
              </div>
          <% end %>
      <% end %>
  <% end %>
</div>

app/views/users/index.html.erb
  <h1>Home Page</h1>


  <br/>

  <div class="">
        <span>Create a status....</span>
        <%= form_for [@cuuser, @post], remote: true do |f| %>
            <p><%= f.text_field :title, :class=>"status_title_input_field", :autocomplete => :off, :placeholder=>"Title ..." %><p/>
            <%= f.text_area :body, :class=>"status_input_field", :autocomplete => :off, :placeholder=>"Write something here....." %><br/>
            <%= f.submit 'Post'%>
        <% end %>
      </div>
  <div class="posts_container">
        <% @all_posts.each do |pst| %>
        <div class="single_post" data-postid="<%= pst.id %>">
          <div class="post_title">
            <% if pst.user.profilepic.present? %>
                <%= link_to image_tag(pst.user.profilepic, :border => 0, :alt => '', :title => pst.user.name), user_path(pst.user), :class => ''%>
            <% else %>
                <%= link_to image_tag("/image/profile-image2.gif", :border => 0, :alt => '', :title => pst.user.name), user_path(pst.user), :class => ''%>
            <% end %>
          <span class="user"> <%= link_to pst.user.email, user_path(pst.user) %> </span><%= pst.title if pst.title %>
          <% if pst.user.id==@cuuser.id %>
                <img class="post_delete" src="/image/cancel.png" />
          <% end %>
          </div>
          <div class="post_body">
            <div class="body_part"><%= pst.body %></div>
          </div>
          <div class="like_comment_part">
            <% if pst.likes.any? %>
                <% already_liked = pst.likes.select {|l| l["user_id"] == @cuuser.id}%>
                    <% if already_liked.any? %>
                        <span style="color: green" class="like">Liked</span>
                    <% else %>
                        <span class="like">Like</span>
                    <% end %>
                <span class="all_likes">
                  <span class="number"><%= pst.likes.count %></span>
                  <span class="unit">
                    <% if pst.likes.count==1 %>
                      Like
                    <% else %>
                      Likes
                    <% end %>
                  </span>
                </span>
            <% else %>
                <span class="like">Like</span>
            <% end %>
            <span class="comment">Comment</span>
          </div>
          <div class="comment_container">
            <div class="comments">
              <% if pst.comments.any? %>
                <% pst.comments.reverse.each do |cmnt|  %>
                  <div class="single_comment">
                    <% if cmnt.user.profilepic.present? %>
                        <%= link_to image_tag(cmnt.user.profilepic, :border => 0, :alt => '', :title => cmnt.user.name), user_path(cmnt.user), :class => ''%>
                    <% else %>
                        <%= link_to image_tag("/image/profile-image2.gif", :border => 0, :alt => '', :title => cmnt.user.name), user_path(cmnt.user), :class => ''%>
                    <% end %>
                    <span class="commenter"><%=link_to cmnt.user.name, user_path(cmnt.user) %></span>
                    <span class="comment_body"> <%= cmnt.body %></span>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
        <% end %>
      </div>

  <div class="post_loader">post loader.........</div>
  <!--<div class="notification_box">-->
    <!--<%#= link_to users_path do %>-->
        <!--<div class="every_notification">-->
          <!--<div class="image_holder">-->
            <!--<%#= image_tag('/image/profile-image2.gif',:class => "notify_image")%>-->
          <!--</div>-->
          <!--<div class="body_holder">-->
            <!--<span class="maker_mane">Maker Name</span>-->
            <!--<span class="body">jdsf dklfjdsfkj dsf dsfsdfsd</span>-->
          <!--</div>-->
          <!--<div style="clear: both"></div>-->
        <!--</div>-->
    <!--<%# end %>-->
  <!--</div>-->

app/views/users/load_notification.js.erb
$('.received_notification_container').html('<%= escape_javascript render("users/load_notification_partial_view") %>');

app/views/users/load_received_friend_request_list.js.erb
$('.received_friend_request_container').html('<%= escape_javascript render("users/load_friend_request") %>');
$('.received_friend_request_container').find('.confirm_request').click(function(){
    var data=$(this).parent().data('userinfo');
    var user_id=data.id;
    $.ajax({
        url: '<%= Rails.application.routes.url_helpers.confirm_friend_request_ajax_users_path %>',
        data: {user_id:user_id},
        type: 'get'
    });
    $(this).parent().remove();
    if($.trim($('.received_friend_request_container').html())=='')
    {
        $('.received_friend_request_container').html('None')
    }
});
$('.received_friend_request_container').find('.cancel_request').click(function(){
    var data=$(this).parent().data('userinfo');
    var user_id=data.id;
    $.ajax({
        url: '<%= Rails.application.routes.url_helpers.cancel_friend_request_ajax_users_path %>',
        data: {user_id:user_id},
        type: 'get'
    });
    $(this).parent().remove();
    if($.trim($('.received_friend_request_container').html())=='')
    {
        $('.received_friend_request_container').html('None')
    }
});

app/views/users/new.html.erb
<h2>Sign up</h2>

<%= form_for @user do |f| %>


    <div class="field">
      <%= f.label :email %><br />
      <%= f.email_field :email, autofocus: true %>
    </div>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name%>
    </div>
    <div class="field">
      <%= f.label :username %><br />
      <%= f.text_field :username%>
    </div>
    <div class="field">
      <%= f.label :password %>
      <% if @validatable %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off" %>
    </div>

    <div class="actions">
      <%= f.submit "Sign up" %>
    </div>
<% end %>

app/views/users/pagination_sample.html.erb
<div>
  <% @users.each do |usr| %>
  <div><%= usr.name %></div>
  <% end %>
</div>
<div><%= paginate @users %></div>

app/views/users/search_friend.js.erb
$('.serched_friend_list_container').html('<%= escape_javascript render("users/searched_friendListLoad") %>');
if('<%= @searched_friend.any? %>'=='true'){
    $('.serched_friend_list_container').show();
}
else{
    $('.serched_friend_list_container').hide();
}

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<%= image_tag(@user.profilepic, :width => 90) if @user.profilepic.present? %>
<br/>
<br/>
<br/>
<br/>
<div class="friend_type_show">
    <% if @friend_comment=='Add Friend' %>
        <div class=""><%= link_to "Add Friend", add_friend_request_users_path(:user_id=>@user.id), :class => 'btn_class'  %> </div>
    <% elsif @friend_comment=='Friend' %>
        <div class="Friend_button btn_class">Friend</div>
    <% elsif @friend_comment=='Confirm or Cancel' %>
        <div class="confirm_or_cancel">
          <%= link_to 'Confirm', confirm_friend_request_users_path(:user_id=>@user.id), :class=>'btn_class confirm' %>
          <%= link_to 'Cancel', cancel_friend_request_users_path(:user_id=>@user.id), :class=>'btn_class cancel' %>
        </div>
    <% elsif @friend_comment=='Request Sent' %>
        <div class="request_sent btn_class">Request Sent</div>
    <% end %>
</div>
<%= link_to "Back to Users", users_path %>

app/views/users/show_all_likes.js.erb
var like_container=$('.single_post .like_comment_part .all_likes');
like_container.each(function(){
    if($(this).hasClass('showalllikesActive')){
        $(this).append('<%= escape_javascript render("users/show_all_likes") %>')
    }
});